to get a reponse

diff --git a/.github/workflows/endpoint.yml b/.github/workflows/endpoint.yml
--- a/.github/workflows/endpoint.yml
+++ b/.github/workflows/endpoint.yml
@@ -26,7 +26,6 @@ jobs:
           mapfile -t files < <(git diff --name-only "$BASE" "$HEAD" | grep '\.json$')
 
           json_array="["
-
           for file in "${files[@]}"; do
             if [ -f "$file" ]; then
               content=$(jq -c . < "$file")  # compact JSON
@@ -40,28 +39,27 @@ jobs:
           echo "$json_array" > files_payload.json
           echo "JSON_PAYLOAD_PATH=files_payload.json" >> $GITHUB_ENV
 
-          - name: Send JSON files to API and check response
-          env:
-            API_URL: https://9d2e-2409-40f0-1048-f538-1502-dd6d-8985-3db2.ngrok-free.app
-          run: |
-            echo "Sending JSON payload to $API_URL..."
-  
-            response=$(curl -s -X POST "$API_URL" \
-              -H "Content-Type: application/json" \
-              --data-binary "@$JSON_PAYLOAD_PATH")
-  
-            echo "API response: $response"
-  
-            status=$(echo "$response" | jq -r '.status')
-            mssg=$(echo "$response" | jq -r '.mssg')
-  
-            echo "Status: $status"
-            echo "Message: $mssg"
-  
-            if [ "$status" != "passed" ]; then
-              echo "❌ Test failed: $mssg"
-              exit 1
-            fi
-  
-            echo "✅ Test passed: $mssg"
-  
+      - name: Send JSON files to API and check response
+        env:
+          API_URL: https://9d2e-2409-40f0-1048-f538-1502-dd6d-8985-3db2.ngrok-free.app
+        run: |
+          echo "Sending JSON payload to $API_URL..."
+
+          response=$(curl -s -X POST "$API_URL" \
+            -H "Content-Type: application/json" \
+            --data-binary "@$JSON_PAYLOAD_PATH")
+
+          echo "API response: $response"
+
+          status=$(echo "$response" | jq -r '.status')
+          mssg=$(echo "$response" | jq -r '.mssg')
+
+          echo "Status: $status"
+          echo "Message: $mssg"
+
+          if [ "$status" != "passed" ]; then
+            echo "❌ Test failed: $mssg"
+            exit 1
+          fi
+
+          echo "✅ Test passed: $mssg"
